# Site settings
title: "Amp - Music Bot"
description: Play music with Slack and Twitter.
keywords: request, music, slack, bot, twitter, jukebox, google cse, spelling correction, google cast, chromecast, spotify, playlist, trackset
author: "Patrick Schroen"
email: ps@ufo.ai
url: "https://ufo.ai/amp/"
cdn: "https://ufo.ai/amp"
app_id: ai.ufo.amp
share_title: Play music with Slack and Twitter
share_description: User generated playlists and party starter! :)
twitter_username: pschroen
ga_ua_id: "UA-51047442-1"

# Build settings
markdown: kramdown
